spring.application.name=agri_manager

# ??????? ?? ?? ????
spring.datasource.url=jdbc:postgresql://localhost:5432/agrimanager_db
spring.datasource.username=postgres
spring.datasource.password=1234

# ????????? Hibernate & PostGIS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ????? ??? PostGIS Dialect ??? ??? ??????????
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

# API Keys
weather.api.key=1751de8a500ec08b994abfcf9be2ab0c

# JWT ?????????
jwt.secret.key=MySuperSecretKeyThatIsVeryLongAndSecure1234567890
jwt.expiration=86400000